/**
 * Booking echo message — the one inbound message the LIFF client sends on the
 * customer's behalf right after a successful booking.
 *
 * Why it exists: LINE only raises an unread badge in LINE OA Chat
 * (https://chat.line.biz) and a push in the LINE OFFICIAL ACCOUNT app for
 * *inbound* messages from a user. The Flex confirmation the server pushes is
 * outbound, so it lands in the chat history without ever notifying the shop,
 * and there is no API to mark a conversation unread from the bot side.
 * Sending one message via `liff.sendMessages()` is the only mechanism that
 * produces a real inbound event, and therefore a real notification.
 *
 * Both the LIFF client (which builds the text) and the webhook (which must
 * recognise it and stay silent) depend on the exact same marker, so it lives
 * in one shared module.
 */

import type { SupabaseClient } from '@supabase/supabase-js';

/** Prefix that marks a message as a booking echo rather than customer input. */
export const BOOKING_ECHO_PREFIX = 'ยืนยันคิว';

/** Separator between echo fields. A middle dot is not something a customer types. */
const ECHO_SEPARATOR = ' · ';

/**
 * Build the echo text sent into the OA chat on the customer's behalf.
 *
 * The customer sees this as their own message, so it has to read like
 * something a person would plausibly send — not a raw log line.
 *
 * @param input - Booking details to show. Blank or '-' fields are dropped.
 * @returns Single-line message text, always starting with {@link BOOKING_ECHO_PREFIX}.
 */
export function buildBookingEchoText(input: {
  queueNumber: string;
  branch: string;
  service: string;
  dateLabel: string;
  time: string;
}): string {
  const clean = (v: string | null | undefined) => {
    const t = (v ?? '').trim();
    return t && t !== '-' ? t : '';
  };

  const head = `${BOOKING_ECHO_PREFIX} ${clean(input.queueNumber) || '-'}`;
  const when = [clean(input.dateLabel), clean(input.time)].filter(Boolean).join(' ');
  const tail = [when, clean(input.service), clean(input.branch)].filter(Boolean);

  return [head, ...tail].join(ECHO_SEPARATOR);
}

/**
 * Detect a booking echo so the webhook can log it without replying.
 *
 * Requires both the prefix and the separator: a customer who genuinely types
 * "ยืนยันคิว" still gets a bot reply, only the generated message is silenced.
 *
 * @param text - Inbound message text from the LINE webhook.
 * @returns true when the message was generated by {@link buildBookingEchoText}.
 */
export function isBookingEcho(text: string): boolean {
  const t = (text ?? '').trim();
  return t.startsWith(BOOKING_ECHO_PREFIX) && t.includes(ECHO_SEPARATOR);
}

/**
 * Read a shop's echo toggle without letting a missing column break the caller.
 *
 * `shops.booking_echo_enabled` ships in migration 202608240002. Until that has
 * run the query errors, and this path is on the customer booking flow — so a
 * failure resolves to the column default (on) instead of bubbling up.
 *
 * @param admin - Supabase client already scoped to read this shop.
 * @param shopId - Shop to read the flag for.
 * @returns true unless the shop explicitly turned the echo off.
 */
export async function isBookingEchoEnabled(admin: SupabaseClient, shopId: string): Promise<boolean> {
  const { data, error } = await admin
    .from('shops')
    .select('booking_echo_enabled')
    .eq('id', shopId)
    .maybeSingle();
  if (error) return true;
  return (data as { booking_echo_enabled?: boolean } | null)?.booking_echo_enabled !== false;
}
